import { supabase } from "@/integrations/supabase/client";

/**
 * MAANG/FAANG-ready AI Engineer roadmap. Users can pick this instead of the
 * sample roadmap on first login. Everything remains editable after seeding.
 */
export const AI_ENGINEER_ROADMAP: Array<{
  title: string;
  outcome: string;
  topics: Array<{ group?: string; title: string }>;
}> = [
  {
    title: "M0 — Software Engineering Foundation",
    outcome: "Become a strong Python Software Engineer.",
    topics: [
      { group: "Python", title: "Python (Beginner → Advanced)" },
      { group: "Python", title: "OOP" },
      { group: "Python", title: "Exception Handling" },
      { group: "Python", title: "Decorators" },
      { group: "Python", title: "Iterators" },
      { group: "Python", title: "Generators" },
      { group: "Python", title: "File Handling" },
      { group: "Tools", title: "Virtual Environments" },
      { group: "Tools", title: "Git" },
      { group: "Tools", title: "GitHub" },
      { group: "Tools", title: "Linux" },
      { group: "DB", title: "SQL" },
      { group: "Backend", title: "REST APIs" },
      { group: "CS", title: "Data Structures (Interview Level)" },
    ],
  },
  {
    title: "M1 — Data Processing & NLP",
    outcome: "Understand how raw text becomes vectors.",
    topics: [
      { title: "NumPy" },
      { title: "Pandas" },
      { title: "Data Cleaning" },
      { title: "Feature Engineering" },
      { title: "Tokenization" },
      { title: "Stop Words" },
      { title: "Lemmatization" },
      { title: "Stemming" },
      { title: "Bag of Words" },
      { title: "TF-IDF" },
      { title: "Word2Vec" },
      { title: "GloVe" },
      { title: "FastText" },
      { title: "Sentence Embeddings" },
      { title: "Transformer Basics" },
    ],
  },
  {
    title: "M2 — Machine Learning",
    outcome: "Understand how ML models learn.",
    topics: [
      { title: "Supervised Learning" },
      { title: "Unsupervised Learning" },
      { title: "Linear Regression" },
      { title: "Logistic Regression" },
      { title: "Decision Trees" },
      { title: "Random Forest" },
      { title: "XGBoost" },
      { title: "SVM" },
      { title: "KMeans" },
      { title: "PCA" },
      { title: "Model Evaluation" },
      { title: "Bias-Variance" },
      { title: "Hyperparameter Tuning" },
    ],
  },
  {
    title: "M3 — Deep Learning",
    outcome: "Understand deep learning architectures.",
    topics: [
      { title: "Neural Networks" },
      { title: "Perceptron" },
      { title: "MLP" },
      { title: "CNN" },
      { title: "RNN" },
      { title: "LSTM" },
      { title: "GRU" },
      { title: "Backpropagation" },
      { title: "Optimizers" },
      { title: "TensorFlow" },
      { title: "PyTorch" },
    ],
  },
  {
    title: "M4 — Large Language Models (LLMs)",
    outcome: "Master LLM fundamentals.",
    topics: [
      { group: "Architecture", title: "Transformer Architecture" },
      { group: "Architecture", title: "Encoder" },
      { group: "Architecture", title: "Decoder" },
      { group: "Architecture", title: "Self Attention" },
      { group: "Architecture", title: "Multi Head Attention" },
      { group: "Architecture", title: "Positional Encoding" },
      { group: "Basics", title: "Tokenization (BPE, SentencePiece)" },
      { group: "Basics", title: "Context Window" },
      { group: "Basics", title: "Embeddings" },
      { group: "Models", title: "GPT" },
      { group: "Models", title: "Gemini" },
      { group: "Models", title: "Claude" },
      { group: "Models", title: "Llama" },
      { group: "Models", title: "Mistral" },
      { group: "Prompting", title: "Prompt Engineering" },
      { group: "Prompting", title: "Zero Shot" },
      { group: "Prompting", title: "Few Shot" },
      { group: "Prompting", title: "Chain of Thought" },
      { group: "Prompting", title: "Hallucination" },
      { group: "Prompting", title: "Temperature" },
      { group: "Prompting", title: "Top-P" },
    ],
  },
  {
    title: "M5 — Retrieval-Augmented Generation (RAG)",
    outcome: "Build production-ready RAG systems.",
    topics: [
      { title: "Document Loaders" },
      { title: "PDF Processing" },
      { title: "Chunking" },
      { title: "Chunk Overlap" },
      { title: "Semantic Chunking" },
      { title: "Embeddings" },
      { title: "Vector Databases" },
      { title: "FAISS" },
      { title: "ChromaDB" },
      { title: "Pinecone" },
      { title: "Weaviate" },
      { title: "Azure AI Search" },
      { title: "Similarity Search" },
      { title: "Hybrid Search" },
      { title: "BM25" },
      { title: "Metadata Filtering" },
      { title: "Re-ranking" },
      { title: "Production RAG" },
      { title: "Query Rewriting" },
      { title: "Parent-Child Retrieval" },
    ],
  },
  {
    title: "M6 — AI Agents",
    outcome: "Build production-grade AI Agents.",
    topics: [
      { title: "LangChain" },
      { title: "LangGraph" },
      { title: "MCP (Model Context Protocol)" },
      { title: "Function Calling" },
      { title: "Tool Calling" },
      { title: "Memory" },
      { title: "Reflection" },
      { title: "Planning" },
      { title: "ReAct" },
      { title: "Multi-Agent Systems" },
      { title: "CrewAI" },
      { title: "AutoGen" },
      { title: "Semantic Kernel" },
      { title: "AgentOps" },
    ],
  },
  {
    title: "M7 — Production AI Engineering",
    outcome: "Deploy secure, scalable production AI systems.",
    topics: [
      { group: "Backend", title: "FastAPI" },
      { group: "Backend", title: "Async Programming" },
      { group: "Backend", title: "REST APIs" },
      { group: "Backend", title: "Authentication" },
      { group: "Backend", title: "WebSockets" },
      { group: "Backend", title: "Background Tasks" },
      { group: "Deployment", title: "Docker" },
      { group: "Deployment", title: "Docker Compose" },
      { group: "Deployment", title: "Multi-stage Builds" },
      { group: "Deployment", title: "Docker Networking" },
      { group: "Deployment", title: "Volumes" },
      { group: "Cloud", title: "Azure Fundamentals" },
      { group: "Cloud", title: "Azure OpenAI" },
      { group: "Cloud", title: "Azure AI Search" },
      { group: "Cloud", title: "Azure Storage" },
      { group: "Cloud", title: "Azure App Service" },
      { group: "Cloud", title: "Azure Container Apps" },
      { group: "Cloud", title: "Azure Functions" },
      { group: "Cloud", title: "Azure Key Vault" },
      { group: "Cloud", title: "Azure Monitor" },
      { group: "Cloud", title: "AWS EC2" },
      { group: "Cloud", title: "AWS ECS" },
      { group: "Cloud", title: "AWS Lambda" },
      { group: "Cloud", title: "AWS Bedrock" },
      { group: "Cloud", title: "GCP Cloud Run" },
      { group: "Cloud", title: "Vertex AI" },
      { group: "CI/CD", title: "GitHub Actions" },
      { group: "CI/CD", title: "Azure DevOps" },
      { group: "CI/CD", title: "Jenkins" },
      { group: "CI/CD", title: "Docker Registry" },
      { group: "CI/CD", title: "Automatic Deployment" },
      { group: "CI/CD", title: "Rollbacks" },
      { group: "Monitoring", title: "Logging" },
      { group: "Monitoring", title: "Metrics" },
      { group: "Monitoring", title: "Tracing" },
      { group: "Monitoring", title: "Prometheus" },
      { group: "Monitoring", title: "Grafana" },
      { group: "Monitoring", title: "OpenTelemetry" },
      { group: "Monitoring", title: "Azure Application Insights" },
      { group: "Security", title: "JWT" },
      { group: "Security", title: "OAuth" },
      { group: "Security", title: "HTTPS" },
      { group: "Security", title: "API Keys" },
      { group: "Security", title: "RBAC" },
      { group: "Security", title: "Secret Management" },
      { group: "Security", title: "Prompt Injection" },
      { group: "Security", title: "Jailbreak Protection" },
      { group: "Security", title: "Rate Limiting" },
      { group: "Security", title: "PII Masking" },
      { group: "Security", title: "Content Filtering" },
      { group: "Scalability", title: "Redis" },
      { group: "Scalability", title: "Caching" },
      { group: "Scalability", title: "Load Balancer" },
      { group: "Scalability", title: "Celery" },
      { group: "Scalability", title: "RabbitMQ" },
      { group: "Scalability", title: "Horizontal Scaling" },
    ],
  },
  {
    title: "M8 — LLMOps & MLOps",
    outcome: "Manage AI systems in production.",
    topics: [
      { title: "MLflow" },
      { title: "LangSmith" },
      { title: "Prompt Versioning" },
      { title: "Experiment Tracking" },
      { title: "Model Registry" },
      { title: "Model Evaluation" },
      { title: "Continuous Training" },
      { title: "Model Monitoring" },
      { title: "Drift Detection" },
      { title: "Cost Optimization" },
    ],
  },
  {
    title: "M9 — Databases",
    outcome: "Choose and use the right database for AI applications.",
    topics: [
      { title: "PostgreSQL" },
      { title: "MongoDB" },
      { title: "Redis" },
      { title: "Elasticsearch" },
      { title: "Neo4j" },
      { title: "Vector Databases" },
    ],
  },
  {
    title: "M10 — AI System Design",
    outcome: "Design enterprise-grade AI systems.",
    topics: [
      { title: "AI Architecture" },
      { title: "Enterprise RAG Design" },
      { title: "AI Agent Architecture" },
      { title: "Event-Driven Systems" },
      { title: "Microservices" },
      { title: "API Gateway" },
      { title: "Message Queues" },
      { title: "Scaling AI Systems" },
      { title: "Cost Optimization" },
      { title: "High Availability" },
      { title: "Disaster Recovery" },
    ],
  },
  {
    title: "M11 — Industry-Level AI Projects",
    outcome: "Build a portfolio that stands out in interviews.",
    topics: [
      { group: "Projects", title: "Enterprise RAG Assistant" },
      { group: "Projects", title: "Multi-Agent Research System" },
      { group: "Projects", title: "AI Resume Reviewer" },
      { group: "Projects", title: "AI Interview Coach" },
      { group: "Projects", title: "AI Code Reviewer" },
      { group: "Projects", title: "AI Document Analyzer" },
      { group: "Projects", title: "AI SQL Assistant" },
      { group: "Projects", title: "AI Customer Support Assistant" },
      { group: "Projects", title: "AI Meeting Summarizer" },
      { group: "Projects", title: "AI Knowledge Base" },
    ],
  },
  {
    title: "M12 — Certifications",
    outcome: "External, resume-visible validation of AI/cloud skills.",
    topics: [
      { group: "Cloud", title: "Azure AI Engineer Associate (AI-102)" },
      { group: "Cloud", title: "Azure Fundamentals (AZ-900)" },
      { group: "Cloud", title: "AWS ML – Specialty" },
      { group: "Cloud", title: "AWS Solutions Architect – Associate" },
      { group: "Cloud", title: "GCP Professional ML Engineer" },
      { group: "ML/DL", title: "DeepLearning.AI — ML Specialization" },
      { group: "ML/DL", title: "DeepLearning.AI — Deep Learning Specialization" },
      { group: "ML/DL", title: "DeepLearning.AI — NLP Specialization" },
      { group: "ML/DL", title: "DeepLearning.AI — Generative AI with LLMs" },
      { group: "LLM", title: "LangChain/LangGraph certification" },
      { group: "LLM", title: "Databricks Generative AI Engineer Associate" },
      { group: "Data", title: "Databricks Data Engineer Associate" },
      { group: "Data", title: "Azure Data Fundamentals (DP-900)" },
    ],
  },
  {
    title: "M13 — Emerging Topics (2025–2026)",
    outcome: "Cover the current AI engineering hiring bar.",
    topics: [
      { group: "Fine-Tuning", title: "LoRA" },
      { group: "Fine-Tuning", title: "QLoRA" },
      { group: "Fine-Tuning", title: "PEFT" },
      { group: "Fine-Tuning", title: "RLHF" },
      { group: "Fine-Tuning", title: "DPO" },
      { group: "Fine-Tuning", title: "Instruction Tuning" },
      { group: "Eval & Safety", title: "RAGAS" },
      { group: "Eval & Safety", title: "DeepEval / promptfoo" },
      { group: "Eval & Safety", title: "LLM-as-a-Judge" },
      { group: "Eval & Safety", title: "NeMo Guardrails / Llama Guard" },
      { group: "Eval & Safety", title: "Red-teaming basics" },
      { group: "Serving", title: "vLLM" },
      { group: "Serving", title: "Text Generation Inference (TGI)" },
      { group: "Serving", title: "Ollama" },
      { group: "Serving", title: "Quantization (GPTQ, AWQ, GGUF)" },
      { group: "Serving", title: "Model Distillation" },
      { group: "Serving", title: "Semantic Caching" },
      { group: "Multimodal", title: "Vision-Language Models" },
      { group: "Multimodal", title: "Image/Audio embeddings" },
      { group: "Multimodal", title: "Whisper basics" },
      { group: "RL", title: "Multi-Armed Bandits" },
      { group: "RL", title: "Markov Decision Processes" },
      { group: "RL", title: "Q-Learning / DQN" },
      { group: "RL", title: "Policy Gradient basics" },
      { group: "Testing", title: "Unit testing LLM pipelines" },
      { group: "Testing", title: "Golden dataset regression testing" },
      { group: "Testing", title: "Load/latency testing" },
    ],
  },
  {
    title: "M14 — Interview Preparation",
    outcome: "Become interview-ready for AI Engineer roles.",
    topics: [
      { group: "Technical", title: "Python" },
      { group: "Technical", title: "SQL" },
      { group: "Technical", title: "Machine Learning" },
      { group: "Technical", title: "Deep Learning" },
      { group: "Technical", title: "LLMs" },
      { group: "Technical", title: "RAG" },
      { group: "Technical", title: "AI Agents" },
      { group: "Technical", title: "Deployment" },
      { group: "Technical", title: "Security" },
      { group: "Technical", title: "System Design" },
      { group: "Behavioral", title: "STAR Method" },
      { group: "Behavioral", title: "Project Explanation" },
      { group: "Behavioral", title: "Leadership" },
      { group: "Behavioral", title: "Problem Solving" },
      { group: "Mock", title: "HR Round" },
      { group: "Mock", title: "Technical Round" },
      { group: "Mock", title: "AI Architecture Round" },
      { group: "Mock", title: "Production Debugging Round" },
    ],
  },
];

export async function seedRoadmap(
  roadmap: typeof AI_ENGINEER_ROADMAP,
): Promise<boolean> {
  const { data: userData } = await supabase.auth.getUser();
  const user = userData.user;
  if (!user) return false;

  const { count, error: cErr } = await supabase
    .from("milestones")
    .select("*", { count: "exact", head: true });
  if (cErr) throw cErr;
  if ((count ?? 0) > 0) return false;

  for (let i = 0; i < roadmap.length; i++) {
    const m = roadmap[i];
    const { data: ms, error: mErr } = await supabase
      .from("milestones")
      .insert({
        title: m.title,
        outcome: m.outcome,
        order_index: i + 1,
        user_id: user.id,
      })
      .select("id")
      .single();
    if (mErr) throw mErr;
    if (!ms) continue;

    const rows = m.topics.map((t, idx) => ({
      milestone_id: ms.id,
      user_id: user.id,
      title: t.title,
      group_label: t.group ?? null,
      order_index: idx + 1,
    }));
    const { error: tErr } = await supabase.from("topics").insert(rows);
    if (tErr) throw tErr;
  }
  return true;
}
