
-- Clear shared seed data
DELETE FROM public.topics;
DELETE FROM public.milestones;

-- Owner columns
ALTER TABLE public.milestones ADD COLUMN user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE;
ALTER TABLE public.topics ADD COLUMN user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE;

-- Auto-generate milestone ids
ALTER TABLE public.milestones ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;

-- Drop old policies
DROP POLICY IF EXISTS "public read milestones" ON public.milestones;
DROP POLICY IF EXISTS "authenticated insert milestones" ON public.milestones;
DROP POLICY IF EXISTS "authenticated update milestones" ON public.milestones;
DROP POLICY IF EXISTS "authenticated delete milestones" ON public.milestones;
DROP POLICY IF EXISTS "public read topics" ON public.topics;
DROP POLICY IF EXISTS "authenticated insert topics" ON public.topics;
DROP POLICY IF EXISTS "authenticated update topics" ON public.topics;
DROP POLICY IF EXISTS "authenticated delete topics" ON public.topics;

-- Per-user policies
CREATE POLICY "own milestones select" ON public.milestones FOR SELECT TO authenticated USING (auth.uid() = user_id);
CREATE POLICY "own milestones insert" ON public.milestones FOR INSERT TO authenticated WITH CHECK (auth.uid() = user_id);
CREATE POLICY "own milestones update" ON public.milestones FOR UPDATE TO authenticated USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);
CREATE POLICY "own milestones delete" ON public.milestones FOR DELETE TO authenticated USING (auth.uid() = user_id);

CREATE POLICY "own topics select" ON public.topics FOR SELECT TO authenticated USING (auth.uid() = user_id);
CREATE POLICY "own topics insert" ON public.topics FOR INSERT TO authenticated WITH CHECK (auth.uid() = user_id);
CREATE POLICY "own topics update" ON public.topics FOR UPDATE TO authenticated USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);
CREATE POLICY "own topics delete" ON public.topics FOR DELETE TO authenticated USING (auth.uid() = user_id);

REVOKE SELECT ON public.milestones FROM anon;
REVOKE SELECT ON public.topics FROM anon;
